apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample2-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satyamskic/argocd-poc.git
    targetRevision: feature1
    path: templates/
    directory:
      recurse: true  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
